
# File: .github/workflows/repo-sync.yml
name: 同步仓库
on:
  schedule:
    - cron: '8 0-16/8 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync-Zhiyi
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ZhiYi-N/Private-Script.git"
          source_branch: "master"
          destination_branch: "Zhiyi"
          github_token: ${{ secrets.PAT }}

      - name: sync-Feizao
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/age174/-.git"
          source_branch: "main"
          destination_branch: "Feizao"
          github_token: ${{ secrets.PAT }}

      - name: sync-Cenbomin
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/CenBoMin/GithubSync.git"
          source_branch: "main"
          destination_branch: "Cenbomin"
          github_token: ${{ secrets.PAT }}

      - name: sync-Caixukun
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/caixukun112/js.git"
          source_branch: "master"
          destination_branch: "Caixukun"
          github_token: ${{ secrets.PAT }}
